<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>12</LangVersion>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.0.0-alpha000</Version>
    <Company>Limbo</Company>
    <Authors>Anders Bjerner</Authors>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Title>Limbo SyntaxHighlighter</Title>
    <Description>Library for syntax highlighting in .NET.</Description>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Limbo.SyntaxHighlighter</PackageId>
    <PackageTags>Limbo, Skybrud, Syntax Highlighting</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/abjerner/Limbo.SyntaxHighlighter/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/abjerner/Limbo.SyntaxHighlighter/</RepositoryUrl>
  </PropertyGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
	  <PackageReference Include="ColorCode.Core" Version="2.0.15" />
	  <PackageReference Include="ColorCode.Html" Version="2.0.15" />
	  <PackageReference Include="Skybrud.Essentials" Version="1.2.0-alpha002" />
  </ItemGroup>

  <!-- Include package icon for NuGet -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>